### ISSUE TITLE
VL request texture로 인한 Memory leak

### ISSUE THREAD

**Issue by HyperCloudWayne** [NaverCloudPlatform/ARCeyeVLSDK#10]
안녕하세요.

VLSDK를 사용한 서비스 앱 개발 중, 현장 테스트에서 앱이 뻗는 현상이 간헐적으로 발생하였습니다 (해당 VLSDK 버전은 1.5.3).

복귀 후, 최신 VLSDK 버전으로 확인해보니, 카메라 텍스처가 서버로 전달되면서 **메모리 누수**가 발생하는 것을 확인하였습니다.

증상 재현에 사용된 scene에는 LogViewer 옵션이 활성된 VLSDKManager만 존재토록 하였으며, APK 빌드는 **윈도우 Unity 2021.3.43** 환경에서 진행되었습니다.

### Case 1
| Target device       | 갤럭시 노트 20 8G |
|:---------------------:|:-----------------:|
| VLSDK               |       1.6.3       |
| VL Interval Initial |               500 |
| VL Interval Passed  |              1000 |
| VL Quality          |       MEDIUM      |

![image](https://github.com/user-attachments/assets/69f296c3-71ca-42fc-ac0e-124bd9abd98c)

위의 조건으로, 약 4분 정도 동작한 결과를 메모리 프로파일러로 확인한 결과입니다. 

### Case 2

| Target device       | 갤럭시 노트 20 8G |
|:---------------------:|:-----------------:|
| VLSDK               |       1.6.3       |
| VL Interval Initial |               250 |
| VL Interval Passed  |              500 |
| VL Quality          |       HIGH      |

![image](https://github.com/user-attachments/assets/8c42d7f1-b257-4adc-9083-f77c9c40017c)

![image](https://github.com/user-attachments/assets/afac2423-23ec-415e-bab8-67ea7cbdd03b)

![image](https://github.com/user-attachments/assets/c5dbd8aa-f5f7-4844-b140-c8eca698347d)

위 조건에서는 최초 요청으로부터 6분 이후, 앱이 종료되었습니다.
확인 한 번 부탁 드립니다.

**Comment by yeongho-jeong** [comment]
안녕하세요 자세한 버그 리포팅 감사합니다. 해당 문제에 대해서는 수정이 진행된 상태이며, VLSDK v1.6.5 배포에 위 문제에 대한 수정 사항이 포함 될 예정입니다. 신규 버전 배포 후 안내 드리도록 하겠습니다.

**Comment by yeongho-jeong** [comment]
Memory leak 문제가 수정 된 v1.6.5 버전이 배포됐습니다.
추가로 Texture 기반 VL 요청 기능이 복원 되었고 AR Dataset 패키지에 대한 가이드도 문서에 추가 되었습니다.
문서의 [3.1 Editor 상에서의 VL 요청](https://ar.naverlabs.com/ARPG/docs/VLSDK_v1.6.5.html#3_1_vl_in_editor:~:text=%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C%20%EA%B0%B1%EC%8B%A0%20%EB%90%A9%EB%8B%88%EB%8B%A4.-,3.1%20Editor%20%EC%83%81%EC%97%90%EC%84%9C%EC%9D%98%20VL%20%EC%9A%94%EC%B2%AD,-VL%20SDK%EB%8A%94) 항목 참고 부탁드립니다.

**Comment by HyperCloudWayne** [comment]
감사합니다. 이슈 종료하겠습니다.
