### ISSUE TITLE
VLSDK의 Texture 기반 Request API 오픈 문의

### ISSUE THREAD

**Issue by HyperCloudWayne** [NaverCloudPlatform/ARCeyeVLSDK#11]
안녕하세요.

VLSDK의 직전 버전인 1.5.3 버전을 사용 중에 있는 와중에, 1.6.3로 업데이트를 진행하였습니다.
ChangeLog를 확인해보니, **Texture기반 Request API**가 삭제되었는데 재오픈 계획은 없을까요?

내부적으로 잘 사용하고 있어, 별도의 Editor 툴까지 구축하였는데 기능이 없어져 아쉽네요 😢

더불어, **AR Dataset 패키지에 대한 가이드 문서** 부탁 드립니다. 현재 버전 문서에는 내용이 없습니다.

**Comment by yeongho-jeong** [comment]
안녕하세요, 해당 기능은 개발 시 AR 환경을 시뮬레이션 하는데 적합하지 않다고 판단되어 1.6.x 버전부터 제거 되었습니다. 

별도의 Editor를 구현하셔서 사용하시는 것은 고려하지 못했네요.. 
차주 배포 예정에 있는 v1.6.5에 해당 기능을 다시 활성화 하여 배포 진행하도록 하겠습니다.

AR Dataset 패키지에 대한 가이드도 차주 배포 시 공식 문서에 함께 업데이트가 될 수 있도록 하겠습니다.

**Comment by HyperCloudWayne** [comment]
감사합니다 👍
