### ISSUE TITLE
NOT_ENOUGH_INLIERS Warning log에 대해 문의드립니다

### ISSUE THREAD

**Issue by HyperCloudWayne** [NaverCloudPlatform/ARCeyeVLSDK#12]
안녕하세요

**VLSDK 1.6.5** 버전을 사용하고 있는 와중에 아래와 같은 로그가 나와, 여쭙습니다.

![image](https://github.com/user-attachments/assets/c3aedd45-656b-4ae0-a8a0-17ccaed09a9b)

VL은 정상적으로 작동하나, 주기적으로 해당 로그가 찍히고 있습니다. 어떤 로그인지 알 수 있을까요?
공식 문서에 별도 설명이 없어 문의 드립니다.

**Comment by yeongho-jeong** [comment]
안녕하세요 해당 로그는 요청된 이미지의 위치를 추정하는데 사용된 데이터의 값이 임계값을 넘지 못한 경우 발생하는 로그입니다.
주변 환경의 상태, 촬영 데이터의 품질, 기기의 움직임 등 다양한 원인으로 인해 해당 로그가 출력될 수 있습니다.

VL 동작에 이상이 없고 수 초마다 한 번씩 출력이 되는 경우라는 해당 로그는 무시하셔도 됩니다.
다만 VL이 정상적으로 동작하지 않으면서 지속적으로 위 로그가 출력되는 경우, 주변 환경이나 촬영 데이터 등의 점검이 필요할 수 있습니다.

**Comment by HyperCloudWayne** [comment]
빠른 답변 감사합니다
