### ISSUE TITLE
VLSDK.framework 관련 문의

### ISSUE THREAD

**Issue by yeosu0107** [NaverCloudPlatform/ARCeyeVLSDK#13]
안녕하세요
ARCeye VLSDK v1.6.5 버전 업데이트 후 iOS App이 업로드가 안되는 문제가 있어 이슈 리포팅을 드립니다.
업로드가 안되는 상황이 치명적이어서 확인 부탁드리겠습니다. 🙏

## 개요
ARCeye VLSDK v1.6.5 업데이트 후 iOS App이 Archive까지는 정상적으로 되나,
업로드 단계에서 Validation fail이 발생해 App을 업로드 할 수 없습니다.

이번에 VLSDK V1.6.5에서 iOS 플랫폼 타겟으로 추가된 `VLSDK.framework` 에서 Validate 에러가 발생합니다.
![image](https://github.com/user-attachments/assets/43dc59fd-ad66-4237-b158-8cde51bc4a13)

## 원인
에러 메시지로 추측해보니, `VLSDK.framework`에 **버전과 빌드넘버가 모두 누락**되어 에러가 발생되고 있는것으로 추측됩니다.

그래서 저희쪽에서 임시로 `VLSDK.framework`의 `info.plist`에서 버전과 빌드넘버를 임시로 부여해서 새로 Archive 후 업로드를 하니 정상적으로 업로드 되었습니다.

## 요청사항
버전과 빌드넘버는 임시로 부여한 것이라 VLSDK에 버전과 빌드넘버를 부여 후 SDK를 새로 배포시주실 수 있는지 문의 드립니다.

**Comment by yeongho-jeong** [comment]
안녕하세요 본 문제에 대해서 동일한 이슈를 전달 받아 내부에서 확인 중에 있습니다.
https://github.com/NaverCloudPlatform/ARCeyeARSDK/issues/19

업로드 된 앱을 다운로드 받아 실행을 하면 문제가 발생하는 경우가 있어 해당 내용도 함께 조치 중에 있으니 대응이 완료 되는대로 패치 진행하도록 하겠습니다.

**Comment by yeosu0107** [comment]
예 빠른 회신 감사합니다.
참고로 저희는 테스트 플라이트에서 다운로드 후 정상 동작이 되었습니다.

xcode 15.4 버전을 사용했고,
bundle version은 1
bundle version string은 1.0.0 을 사용했습니다.

**Comment by yeongho-jeong** [comment]
위 문제가 수정된 v1.7.0 버전이 배포되었습니다. 참고 부탁드립니다
