### ISSUE TITLE
VLSDK.framework v1.7.0 업데이트 후 앱 권한 및 크래시 관련 문의

### ISSUE THREAD

**Issue by yeosu0107** [NaverCloudPlatform/ARCeyeVLSDK#15]
안녕하세요 VLSDK 1.7.0 업데이트 후 iOS에서 크래시가 나 문의를 드립니다.

## 개요
VLSDK 1.7.0 업데이트 후 아래와 같은 로그가 출력 후 크래시가 발생합니다.
```
Initialize DevicePoseTracker
ARCeye.DevicePoseTracker:Initialize(Transform, Config)
ARCeye.VLSDKManager:InitPoseTracker()
ARCeye.VLSDKManager:Initialize()
ARCeye.VLSDKManager:Start()

Init VLSDK Native
VLURL candidates

...

<b>VLSDK version 1.7.0, native 1.8.0</b>
ARCeye.VLSDKManager:Initialize()
ARCeye.VLSDKManager:Start()

This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMotionUsageDescription key with a string value explaining to the user how the app uses this data.
```

## 요청사항
info.plist에 NSMotionUsageDescription 권한을 추가하면 해결이 되는데,
위 권한이 왜 필요한지를 저희가 정확히 알지 못하겠습니다.

AppStore에 업로드할 때 앱에서 해당 권한이 왜 필요한지 입력해야 해서
어떤 목적을 위해 추가된 권한 요청인지 간단하게 공유 부탁드리겠습니다.

**Comment by yeongho-jeong** [comment]
안녕하세요 Motion 권한의 경우 기압계 센서를 사용하기 위해 권한을 요청하고 있습니다. v1.7.0 버전부터는 VLSDK에서 기압계 센서값을 통해 건물의 층 간 이동을 식별할 수 있도록 하는 기능을 제공하고 있습니다. 이를 위해 기압계 센서값과 관련된 권한을 요청하게 되었습니다.

기압계 센서 정보에 접근하기 위해 iOS의 CMAltimeter를 사용하고 있는데요, iOS 17.4 버전 이후부터는 CMAltimeter에 접근하기 위해서는 사용자로부터 Motion 센서에 대한 접근 권한이 필요하게 됩니다. ([관련 자료](https://forums.developer.apple.com/forums/thread/747797))
