### ISSUE TITLE
간혹 VL PASS 후 OnLayerInfoChanged 의 string 값 공백

### ISSUE THREAD

**Issue by njelkom** [NaverCloudPlatform/ARCeyeVLSDK#5]
이미 환경 인식 후 진행 중에 재 인식이 되면서 OnLayerInfoChanged 의 string 값이 공백이 떨어지는 경우가 있습니다.

현재는 공백일 경우 예외 처리를 하고 있는데 예외 처리가 맞는 처리인지 궁금합니다.

아래 로그 첨부 드립니다.

[Debug] [2023-11-20 21:44:55] {"result":"SUCCESS","status":"success","message":"","pose":"1700484294913,true.jpg,-104.522266,16.117055,-20.500209,0.983221,-0.019757,-0.081069,-0.162215","total":935,"inlier":163,"residual":5.746254,"floor":"Unknown","lonLat":"126.65607722897566,37.38187206985964","globalPose":"1700484294913,true.jpg,37.38187206985964,126.65607722897566,20.517791,0.983221,-0.019757,-0.081069,-0.162215","nnPoses":["VL2_1693446845410743.jpg,-104.04319,18.17774,-20.13553,0.847828,-0.029479,-0.027161,-0.528754","VL2_16934468
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
ARCeye.LogViewer:DebugLog (ARCeye.LogLevel,string) (at Assets/VLSDK/Scripts/Debugger/LogViewer.cs:143)
ARCeye.LogViewer:DebugLog (ARCeye.LogLevel,intptr) (at Assets/VLSDK/Scripts/Debugger/LogViewer.cs:128)
NetworkController/<Upload>d__25:MoveNext () (at Assets/VLSDK/Scripts/Network/NetworkController.cs:185)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

(Filename: Assets/VLSDK/Scripts/Debugger/LogViewer.cs Line: 143)

[Info] [2023-11-20 21:44:55] VL Pass
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
ARCeye.LogViewer:DebugLog (ARCeye.LogLevel,string) (at Assets/VLSDK/Scripts/Debugger/LogViewer.cs:148)
ARCeye.LogViewer:DebugLog (ARCeye.LogLevel,intptr) (at Assets/VLSDK/Scripts/Debugger/LogViewer.cs:128)
NetworkController/<Upload>d__25:MoveNext () (at Assets/VLSDK/Scripts/Network/NetworkController.cs:185)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

(Filename: Assets/VLSDK/Scripts/Debugger/LogViewer.cs Line: 148)

[Error] [2023-11-20 21:44:55] Region Code is empty. The requested VL server will be updated soon.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
ARCeye.LogViewer:DebugLog (ARCeye.LogLevel,string) (at Assets/VLSDK/Scripts/Debugger/LogViewer.cs:158)
ARCeye.LogViewer:DebugLog (ARCeye.LogLevel,intptr) (at Assets/VLSDK/Scripts/Debugger/LogViewer.cs:128)
NetworkController/<Upload>d__25:MoveNext () (at Assets/VLSDK/Scripts/Network/NetworkController.cs:185)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

(Filename: Assets/VLSDK/Scripts/Debugger/LogViewer.cs Line: 158)

@@@@@@ OnLayerInfoChanged -> 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
Seerslab.ARCeye.ARManager/<RunTest>d__8:MoveNext () (at Assets/Scripts/ARCeye/ARManager.cs:45)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:Start<Seerslab.ARCeye.ARManager/<RunTest>d__8> (Seerslab.ARCeye.ARManager/<RunTest>d__8&) (at Library/PackageCache/com.cysharp.unitask@d210e3d76a/Runtime/CompilerServices/AsyncUniTaskVoidMethodBuilder.cs:110)
Seerslab.ARCeye.ARManager:RunTest (string)
Seerslab.ARCeye.ARManager:OnLayerInfoChanged (string) (at Assets/Scripts/ARCeye/ARManager.cs:40)
UnityEngine.Events.InvokableCall`1<string>:Invoke (string)
UnityEngine.Events.UnityEvent`1<string>:Invoke (string)
ARCeye.PoseTracker:OnLayerInfoChanged (intptr) (at Assets/VLSDK/Scripts/PoseTracker/PoseTracker.cs:444)
NetworkController/<Upload>d__25:MoveNext () (at Assets/VLSDK/Scripts/Network/NetworkController.cs:185)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

(Filename: Assets/Scripts/ARCeye/ARManager.cs Line: 45)

**Comment by yeongho-jeong** [comment]
VL 성공 인식 이후 `Region Code is empty. The requested VL server will be updated soon`라는 메시지가 출력 되는 것은 비정상적인 동작으로 보입니다. VL 응답이 성공이라면 해당 로그가 출력되어서는 안됩니다.
다음 패키지를 적용한 이후에도 같은 문제가 발생하는지 확인이 필요할 것 같습니다. 같은 문제가 발생할 경우 위에 전달 주신 것과 같은 로그를 첨부 부탁드립니다.

[vl-sdk-1.3.2.unitypackage.zip](https://github.com/NaverCloudPlatform/ARCeyeVLSDK/files/13437829/vl-sdk-1.3.2.unitypackage.zip)
